### ISSUE TITLE
Request: support F-Droid basic app too

### ISSUE THREAD

**Issue by BD9Max** [qianbinbin/fdroid-priv-ext#4] opened 2024-11-12 23:12 UTC
Request: support F-Droid basic app too.

Would it be possible your script work with basic app too?

https://f-droid.org/en/packages/org.fdroid.basic

**Comment by qianbinbin** [comment] 2024-11-13 04:25
I'm afraid not. The extension and client app are fetched directly from https://f-droid.org/ , and the only task of the script is to install them into `/system/` systemlessly. If F-Droid Basic doesn't support privileged extension then we also have no way.

From the description of the basic version
> It targets Android 13 and can do unattended updates without privileged extension or root.

It seems that it can update apps automatically after the apps' first manual installation.

**Comment by BD9Max** [comment] 2024-11-14 17:12
It supports priviledged extension there's a setting for it in the menu.

**Comment by BD9Max** [comment] 2024-11-14 17:14
> 
> > It targets Android 13 and can do unattended updates without privileged extension or root.

Android 9, 10, 11, 12... 14?

Basic is the better of the two F-Droid apps. It has less extra. Like no nearby tab and recent page is better organised.

Basic should be default :)

**Comment by qianbinbin** [comment] 2024-11-14 17:26
If F-Droid Basic supports the privileged extension, just install the module and Basic, and it should work I think?

You can hide F-Droid or remove `/data/adb/modules/fdroid-priv-ext/system/app/F-Droid/F-Droid.apk` if you like.

**Comment by BD9Max** [comment] 2024-11-14 17:35
I tried but couldn't get it to work

**Comment by qianbinbin** [comment] 2024-11-14 17:52
Yeah I found I can't toggle on the priv extension. Looks like we can't do that on Android >=12, see https://gitlab.com/fdroid/fdroidclient/-/issues/2691

**Comment by BD9Max** [comment] 2024-11-14 17:53
^^ I'm going to try that again to see and make sure.

Btw, does priviledged extension install updates to apps if the signature isn't the same?

I sometimes edit the apps a bit to better suit my needs and then I need to sign them myself.

Google play store does update apps even though signature different.

**Comment by BD9Max** [comment] 2024-11-14 23:48
> Yeah I found I can't toggle on the priv extension. Looks like we can't do that on Android >=12, see https://gitlab.com/fdroid/fdroidclient/-/issues/2691

I'm on Android 11. I can turn it ot but it doesn't stay on probably because the extension is for the other app?

**Comment by qianbinbin** [comment] 2024-11-15 09:05
Did you try this [PR](https://gitlab.com/fdroid/privileged-extension/-/merge_requests/75)? It seems they haven't added Basic to the extension whitelist yet.

**Comment by BD9Max** [comment] 2024-11-15 18:19
Hmm haven't they yet added... I cant believe.

Could add with Magisk/ Lsposed?

**Comment by qianbinbin** [comment] 2024-11-16 09:30
As mentioned in https://gitlab.com/fdroid/fdroidclient/-/issues/2593 the developers disabled priv-ext for Basic by design. From https://gitlab.com/fdroid/fdroidclient/-/blob/master/app/src/main/java/org/fdroid/fdroid/Preferences.java?ref_type=heads#L234-238 we can see

```java
    public boolean isPrivilegedInstallerEnabled() {
        // only use priv-ext by default with full flavor, because basic isn't allowed to use it
        // and there's a bug with auto-detection: https://gitlab.com/fdroid/fdroidclient/-/issues/2593
        return preferences.getBoolean(PREF_PRIVILEGED_INSTALLER, BuildConfig.FLAVOR.equals("full"));
    }
```

Actually I've built the priv-ext with Basic enabled in whitelist, but nothing happened.

**Comment by BD9Max** [comment] 2024-11-16 12:48
> As mentioned in https://gitlab.com/fdroid/fdroidclient/-/issues/2593 the developers disabled priv-ext for Basic by design. From https://gitlab.com/fdroid/fdroidclient/-/blob/master/app/src/main/java/org/fdroid/fdroid/Preferences.java?ref_type=heads#L234-238 we can see
> 
> ```java
>     public boolean isPrivilegedInstallerEnabled() {
>         // only use priv-ext by default with full flavor, because basic isn't allowed to use it
>         // and there's a bug with auto-detection: https://gitlab.com/fdroid/fdroidclient/-/issues/2593
>         return preferences.getBoolean(PREF_PRIVILEGED_INSTALLER, BuildConfig.FLAVOR.equals("full"));
>     }
> ```
> 
> Actually I've built the priv-ext with Basic enabled in whitelist, but nothing happened.

Yes I tried with basic and your module - not working:(
I hope you find a solution. Lsposed if not Magisk?

One solution would be to perhaps to rename basic app com.fdroid.fdroid ~ into default :D :D

Neo Store does update even though signature changed so that could be used to update those apps F-Droid aren't updating :/

**Comment by qianbinbin** [comment] 2024-11-16 13:10
I don't think changing the package name will work. You could track their issue or fork the source code to make changes yourself. This issue is beyond the scope of the module, sorry but I'm closing this issue.

**Closed as completed by qianbinbin** 2024-11-16 13:10 UTC
